# Generated by Django 4.2.4 on 2023-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publisher',
            name='date_established',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
