# Generated by Django 4.2.4 on 2023-09-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_publisher_city_publisher_date_established'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='date_established',
            new_name='founded',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='city',
            new_name='headquarters',
        ),
    ]
