# Generated by Django 4.2.4 on 2023-09-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
