# Generated by Django 4.2.4 on 2023-08-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_rename_book_id_book_isbn'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('#0', 'rented'), ('#1', 'returned'), ('#2', 'lost'), ('#3', 'delayed')], max_length=2)),
                ('rent_start_date', models.DateField(help_text='when the book was rented')),
                ('rent_end_date', models.DateField(help_text='deadline,blank=True')),
                ('return_date', models.DateField(blank=True, help_text='return date', null=True)),
                ('rental_status_is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
