# Generated by Django 4.2.4 on 2023-09-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('#0', 'Rented'), ('#1', 'Returned'), ('#2', 'Lost'), ('#3', 'Delayed')], max_length=2),
        ),
    ]
