# Generated by Django 4.2.4 on 2023-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktitle',
            name='genre',
            field=models.CharField(choices=[('DOC', 'Documentary'), ('DRA', 'Drama'), ('PROSE', 'Prose'), ('POEM', 'Poem'), ('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('MYST', 'Mystery'), ('SF', 'Science Fiction')], default='DRA', max_length=5),
        ),
    ]
