# Generated by Django 4.2.4 on 2023-09-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_booktitle_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktitle',
            name='genre',
            field=models.CharField(choices=[('DOC', 'Documentary'), ('DRA', 'Drama'), ('PROSE', 'Prose'), ('POEM', 'Poem'), ('FICTION', 'Fiction'), ('NF', 'Non-Fiction'), ('MYST', 'Mystery'), ('SF', 'Science Fiction')], default='DRA', max_length=7),
        ),
    ]
