# Generated by Django 4.2.4 on 2023-09-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_isbn_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
