# Generated by Django 4.2.4 on 2023-09-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_publication_place_book_publication_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_year',
            new_name='publication_time',
        ),
    ]
