# Generated by Django 4.2.4 on 2023-09-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_rename_publication_year_book_publication_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
