# Generated by Django 4.2.4 on 2023-09-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age_group',
            field=models.CharField(blank=True, choices=[('0-18', '0-18'), ('18-25', '18-25'), ('25-35', '25-35'), ('35-65', '35-65'), ('65+', '65+')], default='', max_length=5),
        ),
    ]
