# Generated by Django 4.2.4 on 2023-08-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ('-created_at',)},
        ),
    ]
