# Generated by Django 4.2.4 on 2023-09-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
